### ISSUE TITLE
Twilio Conversation 2.2

### ISSUE THREAD

**Issue by ahmad-raza** [jedusei/Twilio.Conversations.Xamarin#1]
Hi @jedusei ,

Much appreciate your work! 

Do we have any update coming soon? with latest Twilio Conversation 2.2 Binding?

Thanks,

**Comment by jedusei** [comment]
Hi @ahmad-raza,

Thank you! Yes actually I've had that in my todo list for some time now, but because I've been quite busy at my workplace I had forgotten about it. I'll try to publish an update containing the latest SDKs over the weekend.

**Comment by ahmad-raza** [comment]
Much appreciated! Looking forward to it.

**Comment by jedusei** [comment]
Hello @ahmad-raza,

Unfortunately I cannot publish the update today because my MacBook is not available at the moment. I have updated the Android SDK bindings but I cannot publish the NuGet package without first building the iOS solution, and that requires a MacBook. I'll be able to access the MacBook next Wednesday, so that's when I will publish the update. Sorry for any inconveniences this may cause.

**Comment by jedusei** [comment]
Hi @ahmad-raza.
I've published the update (https://www.nuget.org/packages/Twilio.Conversations.Xamarin/2.0.0-beta1).
Please try it out and let me know if you have any issues.
