### ISSUE TITLE
Question, The changes for new version 2.0.2

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#15]
Hi @jedusei 

Thank you for release new version and it seem iOS does not crashes anymore. However what have you changed for fixing? I have checked [commit history log](https://github.com/jedusei/Twilio.Conversations.Xamarin/commit/da24547eb3cf251ca74cfeb13702a5b37c7af845) and it looks only document has been changed.  So it looks the change you made was happened out of git controlling.

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

I changed the format of the iOS static library that is bundled in the Nuget package.
When you download and extract the Twilio Conversations iOS SDK and open the `TwilioConversationsClient.xcframework` folder, you will see these two folders:

![image](https://user-images.githubusercontent.com/18331712/179479740-3bf603fd-5b58-4be5-a27a-2298af347dba.png)

The first folder contains a version of the SDK that can run on only physical iPhone devices, and the second folder contains a version of the SDK that can only run on the iOS simulator. I mistakenly published the simulator-only SDK, which is why your app was able to run on the simulator but crashed on the physical device. I can't publish the SDK in the first folder either, because that will run on a physical device but crash on the simulator.

So how was I able to make the package work on both simulator and physical device? That's where the [lipo](https://ss64.com/osx/lipo.html) command on MacOS comes in. I used `lipo` to combine both frameworks into one, added the resulting framework as a native reference, built and then published the Nuget package. There are no commits for that because the framework is not included in the repository.

**Comment by NishiokaTakeo** [comment]
HI @jedusei 

Thank you for detailed information. Just for curiosity,  I might missing the steps to build iOS dll after trying several things. I cloned the repo to my local again, and copied SDK to Static Library and press build. Build is success but dll size was just 5kb. I think this dll does not include SDK?

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

No I don't think that DLL includes the SDK. You have to copy the `TwilioConversationsClient.framework` folder that is in either the `ios-arm64` folder or the simulator folder, and place it in the `Native References` folder of the iOS project. It's already referenced in the project file
[here](https://github.com/jedusei/Twilio.Conversations.Xamarin/blob/da24547eb3cf251ca74cfeb13702a5b37c7af845/Twilio.Conversations.iOS/Twilio.Conversations.iOS.csproj#L46), so Visual Studio should automatically include it in the build.

**Comment by NishiokaTakeo** [comment]
Hi @jedusei 

I have copied the `TwilioConversationsClient.framework` folder underneath the the simulator folder.

![Screenshot_071922_113424_AM](https://user-images.githubusercontent.com/2171088/179658903-98424e94-e7e3-4aa0-9aed-5c30841fbc96.jpg)

but it seems not building. VS shows framework.
![Screenshot_071922_113505_AM](https://user-images.githubusercontent.com/2171088/179658974-028a8258-2a74-4a0c-8843-0173d9896836.jpg)

**Comment by jedusei** [comment]
Hi @NishiokaTakeo 

Click on the framework, go to the Properties window and verify that it looks like this:

![image](https://user-images.githubusercontent.com/18331712/179725085-5034455a-085a-41a0-bc40-fd43bf90bf3b.png)
