### ISSUE TITLE
Send Message

### ISSUE THREAD

**Issue by NishiokaTakeo** [jedusei/Twilio.Conversations.Xamarin#2]
I am trying to send a message through Twilio Conversation in Xamarin by [Twilio.Conversations.Xamarin](https://github.com/jedusei/Twilio.Conversations.Xamarin).

How can I send a new message? There is IConversation.SendMessageAsync() method but it takes IMessageOption interface and I honestly do not know what kind of implementation is needed.

Read many hours in Google but it does not help for me.

**Comment by slimethefrozen** [comment]
I use this to create the IMessageOption on iOS

```
var options = new TCHMessageOptions().WithBody(body);
```
Where body is the text of the message.

On Android I use this:

```
var options = IMessage.Options().WithBody(body);
```

Hope that helps.

**Comment by NishiokaTakeo** [comment]
Really thank you for a quick response!

**Comment by jedusei** [comment]
Hi @slimethefrozen @NishiokaTakeo 

I've published a new release, which contains a number of breaking changes, so these methods won't work in the latest version and above (>= 2.0.0). Please see [this](https://github.com/jedusei/Twilio.Conversations.Xamarin/releases/tag/2.0.0) for more information.

The breaking change that specifically affects sending messages is mentioned in the Twilio docs:
[Android](https://www.twilio.com/docs/conversations/android/changelog#breaking-changes): `Message.Options and Conversation.sendMessage(options) are removed. Use Conversation.prepareMessage instead.`
[iOS](https://www.twilio.com/docs/conversations/ios/changelog#changes_4): `New method to build a message: [TCHConversation prepareMessage]`

I encourage you to upgrade to the [latest version](https://www.nuget.org/packages/Twilio.Conversations.Xamarin/2.0.0), because it's been a while since I last updated the package, and there have been many improvements in the Twilio SDKs under-the-hood.
